# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Release

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o ./dist/catchat_linux_amd64 ./cmd/main.go

      - name: Build Linux 386
        run: GOOS=linux GOARCH=386 go build -o ./dist/catchat_linux_386 ./cmd/main.go

      - name: Build Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build -o ./dist/catchat_linux_arm64 ./cmd/main.go

      - name: Build Linux ARM32
        run: GOOS=linux GOARCH=arm go build -o ./dist/catchat_linux_arm32 ./cmd/main.go

      - name: Build Darwin AMD64
        run: GOOS=darwin GOARCH=amd64 go build -o ./dist/catchat_darwin_amd64 ./cmd/main.go

      - name: Build Darwin ARM64
        run: GOOS=darwin GOARCH=arm64 go build -o ./dist/catchat_darwin_arm64 ./cmd/main.go

      - name: Build Windows 386
        run: GOOS=windows GOARCH=386 go build -o ./dist/catchat_windows_386.exe ./cmd/main.go

      - name: Build Windows AMD64
        run: GOOS=windows GOARCH=amd64 go build -o ./dist/catchat_windows_amd64.exe ./cmd/main.go

      - name: Build Windows ARM32
        run: GOOS=windows GOARCH=arm go build -o ./dist/catchat_windows_arm32.exe ./cmd/main.go

      - name: Build Windows ARM64
        run: GOOS=windows GOARCH=arm64 go build -o ./dist/catchat_windows_arm64.exe ./cmd/main.go

      - name: Build Windows AMD64
        run: GOOS=windows GOARCH=amd64 go build -o ./dist/catchat_windows_amd64.exe ./cmd/main.go

      - name: Upload Build Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/catchat_linux_amd64
            ./dist/catchat_linux_386
            ./dist/catchat_linux_arm64
            ./dist/catchat_linux_arm32
            ./dist/catchat_darwin_amd64
            ./dist/catchat_darwin_arm64
            ./dist/catchat_windows_386.exe
            ./dist/catchat_windows_amd64.exe
            ./dist/catchat_windows_arm32.exe
            ./dist/catchat_windows_arm64.exe
            ./dist/catchat_windows_amd64.exe
