# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o ./dist/linux_amd64 ./cmd/main.go

      - name: Upload to Release
        # You may pin to the exact commit or the version.
        # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
        uses: Shopify/upload-to-release@v1.0.1
        with:
          # Artifact name
          name: catchat_${{ github.ref_name }}_linux_amd64
          # Path to the file to upload
          path: ./dist/linux_amd64
          # Content type for the file
          content-type: application/octet-stream
          # secrets.GITHUB_TOKEN
          repo-token: ${{ secrets.GITHUB_TOKEN }}
